---
abstract: ~
author:
  - 'John BEPPU <beppu {at} cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 6.42
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 1.00'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Rhetoric-Theme-SandStone
no_index:
  directory:
    - inc
    - share
    - t
    - xt
requires:
  Method::Signatures::Simple: 0
  Squatting: 0.8
  Template: 0
resources:
  license: http://dev.perl.org/licenses/
  repository: origin
version: 0.04
